--- #YAML:1.0
name:               IO-Socket-Socks-Wrapper
version:            0.04
abstract:           Allow any perl package to work through a socks proxy
author:
    - Oleg G <oleg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket::Socks:  0.4
    Test::More:         0.88
resources:
    repository:  https://github.com/olegwtf/p5-IO-Socket-Socks-Wrapper
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
